apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-service
data:
  DB_HOST: "10.100.13.221"
  DB_PORT: "5432"
  DB_NAME: postgres
  DB_USER: postgres

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  DB_PASSWORD: MTIzNDU2